import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import MyLayout from "@/app/Components/MyLayout";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link rel="manifest" href="/manifest.json" />
        <link rel="apple-touch-icon" href="/icon-512x512.png"></link>
        <link rel="icon" href="/icon-256x256.png" />
        <title>EpiRoom</title>
      </head>
      <body className={inter.className}>
        <MyLayout>{children}</MyLayout>
      </body>
    </html>
  );
}
